### ISSUE TITLE
Fixuid may slow php init when using global vendor

### ISSUE THREAD

**Issue by PhakkyoC** [gfi-centre-ouest/generator-docker-devbox#19]
Modifications à faire dans la feature php

Dockerfile

```
RUN mkdir -p "$COMPOSER_HOME/cache" \
&& mkdir -p "$COMPOSER_HOME/vendor" \
&& chown -R www-data:www-data $COMPOSER_HOME \
&& chown -R www-data:www-data /var/www
```

fixuid.yml

```
paths:
  - /
  - /composer/cache
  - /composer/vendor
```

docker-compose.yml

```
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/.docker/php/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini'
      - 'php-composer-cache:/composer/cache'
      - 'php-composer-vendor:/composer/vendor'
...
volumes:
  php-composer-cache: null
  php-composer-vendor: null
```
